name: Streamlit Keep Alive

on:
  schedule:
      # Se ejecuta cada 6 horas (puedes cambiarlo si lo deseas)
      - cron: '0 */6 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Visitar URL de la aplicación
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://incidencias-2026.streamlit.app/' # Reemplaza con tu enlace de Streamlit Cloud
          method: 'GET'
