name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Visitar URL de la aplicación
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://incidencias-2026.streamlit.app/'
          method: 'GET'
          timeout: 30000        # Aumenta el tiempo de espera a 30 segundos (30000 ms)
          customHeaders: '{"User-Agent": "GitHub-Actions-Keep-Alive"}'
