name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a la aplicación
        run: |
          URL="https://incidencias-2026.streamlit.app/"
          echo "Visitando la URL: $URL"
          curl -L --max-redirs 5 -s -o /dev/null -w "Código HTTP recibido: %{http_code}\n" "$URL"
